name: mymemory_translate
description: "A simple translation API that uses the MyMemory translate REST API."
version: 1.0.2
homepage: https://github.com/alettsy/mymemory_translate
repository: https://github.com/alettsy/mymemory_translate

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  http: ^1.2.1

dev_dependencies:
  test: ^1.25.2
  mockito: ^5.4.4
  build_runner: ^2.4.8
  lints: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
